# This is a basic workflow to help you get started with Actions

name: SimpleDll CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-job:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore SimpleDll.sln
      
    - name: Build
      run: dotnet build SimpleDll.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish SimpleDll.sln -f net8.0 --configuration Release --no-build --output ./publish
      
    - name: Save output
      uses: actions/upload-artifact@v4
      with:
        name: simple-dlls
        path: ./publish
